### ISSUE TITLE
Parsing of `<=`

### ISSUE THREAD

**Issue by dpsanders** [JuliaDiffEq/ModelingToolkit.jl#101]
Instead of
```jl
julia> @Unknown x y
(x, y)

julia> ex = x^2 + y^2 <= 1
(x ^ 2 + y ^ 2 < 1) | false

julia> dump(ex)
Operation
  op: | (function of type typeof(|))
  args: Array{Expression}((2,)) Expression[x ^ 2 + y ^ 2 < 1, Constant(false)]
```
could this be parsed as something like 
```jl
Condition(<, x^2 + y^2, 1)
```
with a new `Condition` type?

**Comment by HarrisonGrodin** [comment]
First, I believe the initial parsing is a bug (due to our implementation of `==`). The `<=` method is the standard one from `Base`:
```julia
<=(x, y) = (x < y) | (x == y)
```

`ex` should be `(x ^ 2 + y ^ 2 < 1) | (x ^ 2 + y ^ 2 == 1)`.

---

I like the idea of having a typed AST, with one node corresponding to numerical expressions and another (here, `Condition`) corresponding to boolean expressions.

**Comment by HarrisonGrodin** [comment]
Related: #38

**Comment by dpsanders** [comment]
This does not seem to be fixed yet:
```
julia> operation = x^2 + y^2 <= 1 
(x ^ 2 + y ^ 2 < 1) | false
```

**Comment by HarrisonGrodin** [comment]
I get the correct behavior on `master`:
```julia
julia> @variables x y
(x, y)

julia> x^2 + y^2 <= 1
(x ^ 2 + y ^ 2 < 1) | (x ^ 2 + y ^ 2 == 1)
```

**Comment by dpsanders** [comment]
Sorry I forgot to update to master.

But I think the result should just be
```
julia> x^2 + y^2 <= 1
x ^ 2 + y ^ 2 <= 1
```
i.e. an `Operation` with `<=` as `op`. 

What is the benefit of separating the two cases like this?

**Comment by HarrisonGrodin** [comment]
The casing is done automatically, based on the fallback implementation from `Base`:
```julia
# Base
<=(x, y) = (x < y) | (x == y)
```

We don't (currently) explicitly define `<=`, so it hits this definition and subsequently applies our overloads for `<`, `==`, and `|`.

Whether or not this is a good idea has yet to be determined; we haven't done enough in ModelingToolkit around boolean conditions to be able to tell. For now, it seems reasonable to leave it as-is (since we have to handle `<`, `==`, and `|` anyways), but if it seems helpful to overload `<=` specifically, it should be easy to do.
