### ISSUE TITLE
Build DiffEqSystem out of Expressions

### ISSUE THREAD

**Issue by ivborissov** [JuliaDiffEq/ModelingToolkit.jl#44]
Hi, @ChrisRackauckas , @YingboMa 
I am working with a DB where ODE models (parameters, diffeqs, init values, etc) are stored in a language neutral form. So, I can get all the components of `ODEProblem` from DB and convert (parse) them in Julia to `Expressions` like:
```
ex = quote
    v1 = k1*A*comp1
    dA = -v1/comp1
    dB = v1/comp1
end
params = (:k1, :comp1)
depend_vars = (:A, :B)
```
The interface I am looking for is a way to turn such input to `DiffEqSystem` and `ODEProblem`. Is it already supported in macro-free version?

**Comment by ChrisRackauckas** [comment]
I assigned @YingboMa here since he setup the expression parsing that you can see in this test:

https://github.com/JuliaDiffEq/SciCompDSL.jl/blob/master/test/internal.jl

But I think that right now that needs to know the variable context. A version of parsing where you can pass in what names correspond to what kinds of variables, and have a bunch of stuff defined/returned would be good to have, and @YingboMa 's tooling should already be close.

**Comment by ChrisRackauckas** [comment]
We should put this as a lower priority until some other things stabilize, otherwise it will break too easily.

**Comment by ChrisRackauckas** [comment]
We're kicking this as the job for a macro. Maybe we can include a macro in the base package, but this is distinct from the job of the IR.
