### ISSUE TITLE
Ambiguity error with power of a variable

### ISSUE THREAD

**Issue by dpsanders** [JuliaDiffEq/ModelingToolkit.jl#66]
```jl
julia> t = IndependentVariable(:t)
IndependentVariable(t)

julia> t^4
ERROR: MethodError: ^(::ModelingToolkit.Variable, ::Int64) is ambiguous. Candidates:
  ^(x::ModelingToolkit.Expression, y::Number) in ModelingToolkit at /Users/dpsanders/.julia/v0.6/MacroTools/src/utils.jl:260
  ^(x::Number, p::Integer) in Base at intfuncs.jl:198
Possible fix, define
  ^(::ModelingToolkit.Expression, ::Integer)
Stacktrace:
 [1] literal_pow(::Base.#^, ::ModelingToolkit.Variable, ::Type{Val{4}}) at ./intfuncs.jl:208
```

**Comment by chakravala** [comment]
This is related to #65, I'm going to look into this tomorrow

**Comment by ChrisRackauckas** [comment]
Just as a fair warning, @dpsanders I wouldn't use this package yet. It's not ready but I'll announce when it is. Until then, I won't guarantee that master is a stable place to be.

**Comment by chakravala** [comment]
By the way, I have encountered a similar issue in Reduce.jl when extending the `^` method, so I know what kind of solution is necessary for this. However, since I have not used `MacroTools` before and did everything with custom code myself in Reduce, I need to investigate further before I have the exact soltuion for this issue.

**Comment by ChrisRackauckas** [comment]
This issue is because https://github.com/JuliaDiffEq/ModelingToolkit.jl/blob/master/src/ModelingToolkit.jl#L20 . 

```julia
abstract type Expression <: Number end
```

I was wondering if that was a bad assumption or not. By being a `Number` an expression can go into any code that accepts numbers, and since it has the right dispatches it'll be fine. But this seems to cause ambiguities easily. We can either drop this or add more dispatches during function registration. It might just be best to drop `<: Number`.

**Comment by chakravala** [comment]
Aha, so you are getting the method names for `^` from `DiffRules.diffrules()`, this wasn't immediately obvious to me.

**Comment by chakravala** [comment]
So, using the `@register` method, you would have to be able to do
```Julia
@register Base.:^(a::Expression,b::T) where T <: Integer
```
but this type of `sig` is not able to be handled by `@register` yet

**Comment by ChrisRackauckas** [comment]
It is exactly what's causing the issue, see the ambiguity it picks up. We can add in dispatches for `Integer`, but we'd also need to dispatch with all combinations of `Integer` and `AbstractFloat` to get Base types right, and any future number type which isn't categorized into those won't work. That's starting to sound like a whole lot of dispatches for something that would only ever be a partial solution.

**Comment by chakravala** [comment]
From experience, I can say you are going to have to deal with a bunch of ambiguitiesl like this one, as I had to do in `Reduce` as well. You can get an idea of how many specialized method definitions I had to make from my source code https://github.com/chakravala/Reduce.jl/blob/master/src/args.jl#L153-L156

**Comment by ChrisRackauckas** [comment]
`<: Number` is essential usage in generic routines like generic linear algebra. I guess this is why it worked so well for SymEngine and we probably need to keep it.
