### ISSUE TITLE
Use "variable" instead of "unknown"

### ISSUE THREAD

**Issue by dpsanders** [JuliaDiffEq/ModelingToolkit.jl#99]
I suggest to use the word "variable" instead of "unknown".

**Comment by HarrisonGrodin** [comment]
I'd be fine with either one.

The reasoning behind "unknown"/"parameter" was to make it clear that the former was to be solved for and the latter is to be substituted in, since this is the interpretation taken during automatic variable extraction in system construction. Note that this distinction corresponds precisely with the `known` field of `Variable`:
https://github.com/JuliaDiffEq/ModelingToolkit.jl/blob/02edf049d0b2aa25b4869e1afea67969e2096fcc/src/variables.jl#L4-L8

If "variable" carries the same connotation, I'd be happy to switch it. @ChrisRackauckas Thoughts?

**Comment by ChrisRackauckas** [comment]
The unknowns in an equation are usually referred to as the variables, so I think it makes sense. Maybe that struct is what's named incorrectly. It's really a term in the equation? I don't want to overlap with Terms.jl if we don't need to though.

**Comment by HarrisonGrodin** [comment]
I don't think calling it a "term" is the best choice, since that often refers to an entire expression tree (a la Terms.jl). The closest description I can think of would be "symbolic variable" or "symbolic placeholder".

Since it seems to be clear that "variables" are to be solved for, we can rename "unknown" to "variable", with "parameter" as a synonym for "known variable".
